"""
app/services/_prompt_expand.py  (protected helper)

Translates vocabulary in Russian, Uzbek, Arabic, Turkish, Chinese prompts
into English descriptors before passing to the image model.
"""
from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Vocabulary maps  (language → {native_word: english_descriptor})
# ---------------------------------------------------------------------------

_RU: dict[str, str] = {
    "закат":    "golden sunset warm orange red sky horizon",
    "рассвет":  "dawn sunrise soft pink purple morning sky",
    "небо":     "vast open sky",
    "облака":   "dramatic clouds",
    "море":     "ocean sea with waves",
    "река":     "flowing river reflections",
    "лес":      "dense forest tall trees",
    "гора":     "majestic mountain peak",
    "горы":     "mountain range snow-capped peaks dramatic",
    "степь":    "vast open steppe grassland endless horizon wind",
    "пустыня":  "desert sand dunes dry heat",
    "снег":     "snow covered landscape white winter",
    "туман":    "mysterious fog and mist ethereal",
    "звёзды":   "starry night sky milky way galaxy",
    "звезды":   "starry night sky milky way galaxy",
    "луна":     "full moon glowing silver light",
    "солнце":   "bright shining sun rays warm",
    "цветы":    "colorful blooming flowers garden",
    "дерево":   "ancient tall tree majestic",
    "водопад":  "powerful waterfall cascading mist",
    "озеро":    "calm reflective lake serene",
    "волк":     "lone wolf fierce wild",
    "медведь":  "brown bear powerful wild",
    "орёл":     "eagle soaring wings spread sky",
    "орел":     "eagle soaring wings spread sky",
    "лошадь":   "majestic horse running mane flowing",
    "кони":     "wild horses galloping mane flowing",
    "тигр":     "fierce tiger striped jungle",
    "дракон":   "dragon fire scales wings fantasy",
    "девушка":  "young beautiful woman",
    "воин":     "warrior battle-ready armor",
    "рыцарь":   "armored knight medieval",
    "грусть":   "melancholic sad mood somber tones",
    "радость":  "joyful bright cheerful warm atmosphere",
    "тишина":   "peaceful serene silent calm",
    "душа":     "soulful spiritual deeply emotional ethereal",
    "мечта":    "dreamlike ethereal surreal soft light",
    "тайна":    "mysterious secret hidden ancient",
    "золотой":  "golden shimmering warm",
    "золотая":  "golden shimmering warm",
    "красный":  "vivid deep red",
    "синий":    "deep rich blue",
    "зелёный":  "lush vibrant green",
    "белый":    "pure brilliant white",
    "чёрный":   "deep matte black",
    "москва":   "Moscow Russia Red Square Kremlin golden domes",
    "байкал":   "Lake Baikal Siberia crystal blue water",
    "замок":    "medieval stone castle fortress dramatic",
    "церковь":  "Russian Orthodox church colorful onion domes",
    "ночь":     "night time dark moonlit",
    "зима":     "winter cold snow ice frozen",
    "лето":     "summer warm green sunny vibrant",
    "весна":    "spring fresh blossoming flowers new life",
    "осень":    "autumn fall golden orange leaves",
    "древний":  "ancient old historical worn stone",
    "огромный": "enormous massive towering",
    "красивый": "beautiful stunning gorgeous",
    "мрачный":  "gloomy dark somber brooding",
    "дикий":    "wild untamed raw primal",
    "одинокий": "lone solitary isolated",
    "величественный": "majestic grand impressive awe-inspiring",
}

_UZ: dict[str, str] = {
    "quyosh":    "bright shining sun warm rays",
    "oy":        "glowing full moon silver light",
    "yulduzlar": "starry night sky milky way stars",
    "osmon":     "vast open sky blue",
    "tog":       "majestic mountain peak rocky",
    "tog'":      "majestic mountain peak rocky",
    "toglar":    "mountain range dramatic snow peaks",
    "tog'lar":   "mountain range dramatic snow peaks",
    "daryo":     "flowing river peaceful reflections",
    "ko'l":      "calm serene lake reflections",
    "dengiz":    "ocean sea waves horizon",
    "cho'l":     "desert sand dunes hot dry",
    "qor":       "snow white landscape winter",
    "gul":       "beautiful blooming flower",
    "gullar":    "colorful flowers blooming garden",
    "bo'ri":     "lone wolf fierce wild",
    "burgut":    "eagle soaring wings spread majestic",
    "sher":      "powerful lion savanna mane",
    "tuya":      "camel desert Silk Road caravan",
    "navro'z":   "Navruz spring festival Uzbekistan colorful atlas dresses celebrations flowers festive",
    "navruz":    "Navruz spring festival Uzbekistan colorful atlas dresses celebrations flowers festive",
    "registon":  "Registan square Samarkand blue mosaic tilework Islamic architecture historical",
    "samarqand": "ancient Samarkand city Silk Road blue domes minarets historical architecture",
    "buxoro":    "ancient Bukhara historic walled city Kalon minaret tower desert sunset",
    "xiva":      "Khiva Uzbekistan ancient Ichan-Kala walled city blue tile minarets",
    "ipak yo'li":"Silk Road ancient trade route Central Asia camels merchants desert",
    "karvon":    "caravan camels merchants crossing vast desert Silk Road sunset",
    "atlas":     "colorful Uzbek ikat atlas silk vibrant geometric patterns traditional textile",
    "chimyon":   "Chimgan mountains Uzbekistan dramatic snow peaks green pine valleys",
    "masjid":    "beautiful mosque blue dome minaret Islamic geometric tilework architecture",
    "oltin":     "golden shimmering warm luxurious",
    "qizil":     "vivid deep red",
    "ko'k":      "deep rich blue",
    "yashil":    "lush vibrant green",
    "oq":        "pure brilliant white",
    "qora":      "deep black dark",
    "sariq":     "bright yellow warm sunny",
    "tun":       "night dark moonlit",
    "qish":      "winter cold snowy frozen landscape",
    "yoz":       "summer warm sunny vibrant green",
    "bahor":     "spring fresh blossoming flowers new life",
    "kuz":       "autumn golden orange falling leaves",
    "ulkan":     "enormous massive towering grand",
    "qadimiy":   "ancient old historical",
    "chiroyli":  "beautiful stunning gorgeous",
    "yolg'iz":   "lone solitary isolated single",
    "buyuk":     "great magnificent legendary",
    "sokin":     "calm peaceful quiet serene",
    "go'zal":    "beautiful stunning",
}

_AR: dict[str, str] = {
    "غروب":   "golden sunset warm orange sky horizon",
    "شروق":   "dawn sunrise soft pink purple morning sky",
    "سماء":   "vast open sky blue",
    "سحاب":   "dramatic clouds",
    "بحر":    "ocean sea waves horizon",
    "نهر":    "flowing river peaceful reflections",
    "غابة":   "dense forest tall trees",
    "جبل":    "majestic mountain peak rocky",
    "جبال":   "mountain range dramatic snow peaks",
    "صحراء":  "desert sand dunes hot dry",
    "ثلج":    "snow white landscape winter",
    "ضباب":   "mysterious fog and mist ethereal",
    "نجوم":   "starry night sky milky way stars",
    "قمر":    "full moon glowing silver light",
    "شمس":    "bright shining sun rays warm",
    "زهور":   "colorful blooming flowers garden",
    "شجرة":   "ancient tall tree majestic",
    "شلال":   "powerful waterfall cascading mist",
    "بحيرة":  "calm serene lake reflections",
    "ذئب":    "lone wolf fierce wild",
    "نسر":    "eagle soaring wings spread majestic",
    "أسد":    "powerful lion mane savanna",
    "تنين":   "dragon fire scales wings fantasy",
    "فارس":   "armored knight medieval warrior",
    "ليل":    "night time dark moonlit",
    "شتاء":   "winter cold snowy frozen landscape",
    "صيف":    "summer warm sunny vibrant green",
    "ربيع":   "spring fresh blossoming flowers new life",
    "خريف":   "autumn golden orange falling leaves",
    "قلعة":   "medieval stone castle fortress dramatic",
    "مدينة":  "city skyline urban bustling vibrant",
    "ذهبي":   "golden shimmering warm luxurious",
    "أحمر":   "vivid deep red",
    "أزرق":   "deep rich blue",
    "أخضر":   "lush vibrant green",
    "أبيض":   "pure brilliant white",
    "أسود":   "deep matte black",
    "جميل":   "beautiful stunning gorgeous",
    "قديم":   "ancient old historical worn stone",
    "ضخم":    "enormous massive towering grand",
    "غامض":   "mysterious secret hidden ancient",
    "خيال":   "fantasy magical dreamlike ethereal",
    "مكة":    "Mecca holy city Grand Mosque golden",
    "دبي":    "Dubai futuristic skyline modern towers desert",
    "القاهرة":"Cairo Egypt ancient pyramids desert Nile",
}

_TR: dict[str, str] = {
    "gün batımı":  "golden sunset warm orange sky horizon",
    "gündoğumu":   "dawn sunrise soft pink purple morning sky",
    "gökyüzü":     "vast open sky blue dramatic",
    "bulutlar":    "dramatic clouds stormy",
    "deniz":       "ocean sea waves horizon blue",
    "nehir":       "flowing river peaceful reflections",
    "orman":       "dense forest tall trees green",
    "dağ":         "majestic mountain peak rocky",
    "dağlar":      "mountain range dramatic snow peaks",
    "çöl":         "desert sand dunes hot dry",
    "kar":         "snow white landscape winter",
    "sis":         "mysterious fog and mist ethereal",
    "yıldızlar":   "starry night sky milky way stars",
    "ay":          "full moon glowing silver light",
    "güneş":       "bright shining sun rays warm",
    "çiçekler":    "colorful blooming flowers garden",
    "şelale":      "powerful waterfall cascading mist",
    "göl":         "calm serene lake reflections",
    "kurt":        "lone wolf fierce wild",
    "kartal":      "eagle soaring wings spread majestic",
    "aslan":       "powerful lion mane savanna",
    "ejderha":     "dragon fire scales wings fantasy",
    "şövalye":     "armored knight medieval warrior",
    "gece":        "night time dark moonlit",
    "kış":         "winter cold snowy frozen landscape",
    "yaz":         "summer warm sunny vibrant green",
    "ilkbahar":    "spring fresh blossoming flowers new life",
    "sonbahar":    "autumn golden orange falling leaves",
    "kale":        "medieval stone castle fortress dramatic",
    "şehir":       "city skyline urban bustling vibrant",
    "altın":       "golden shimmering warm luxurious",
    "kırmızı":     "vivid deep red",
    "mavi":        "deep rich blue",
    "yeşil":       "lush vibrant green",
    "beyaz":       "pure brilliant white",
    "siyah":       "deep matte black",
    "güzel":       "beautiful stunning gorgeous",
    "antik":       "ancient old historical worn stone",
    "devasa":      "enormous massive towering grand",
    "gizemli":     "mysterious secret hidden ancient",
    "istanbul":    "Istanbul Turkey Bosphorus Blue Mosque Hagia Sophia historical",
    "kapadokya":   "Cappadocia Turkey fairy chimneys hot air balloons dramatic landscape",
    "pamukkale":   "Pamukkale Turkey white travertine terraces thermal pools",
}

_ZH: dict[str, str] = {
    "日落": "golden sunset warm orange red sky horizon",
    "日出": "dawn sunrise soft pink purple morning sky",
    "天空": "vast open sky blue dramatic",
    "云":   "dramatic clouds stormy",
    "大海": "ocean sea waves horizon blue",
    "河流": "flowing river peaceful reflections",
    "森林": "dense forest tall trees green",
    "山":   "majestic mountain peak rocky",
    "山脉": "mountain range dramatic snow peaks",
    "沙漠": "desert sand dunes hot dry",
    "雪":   "snow white landscape winter",
    "雾":   "mysterious fog and mist ethereal",
    "星星": "starry night sky milky way stars",
    "月亮": "full moon glowing silver light",
    "太阳": "bright shining sun rays warm",
    "花":   "colorful blooming flowers garden",
    "瀑布": "powerful waterfall cascading mist",
    "湖":   "calm serene lake reflections",
    "狼":   "lone wolf fierce wild",
    "鹰":   "eagle soaring wings spread majestic",
    "龙":   "Chinese dragon majestic scales fantasy serpent",
    "武士": "samurai warrior traditional armor Japan",
    "夜晚": "night time dark moonlit",
    "冬天": "winter cold snowy frozen landscape",
    "夏天": "summer warm sunny vibrant green",
    "春天": "spring fresh blossoming flowers new life",
    "秋天": "autumn golden orange falling leaves",
    "城堡": "castle fortress dramatic medieval stone",
    "城市": "city skyline urban bustling vibrant neon",
    "金色": "golden shimmering warm luxurious",
    "红色": "vivid deep red",
    "蓝色": "deep rich blue",
    "绿色": "lush vibrant green",
    "白色": "pure brilliant white",
    "黑色": "deep matte black",
    "美丽": "beautiful stunning gorgeous",
    "古老": "ancient old historical worn stone",
    "巨大": "enormous massive towering grand",
    "神秘": "mysterious secret hidden ancient",
    "长城": "Great Wall of China ancient stone mountains mist",
    "故宫": "Forbidden City Beijing China imperial palace traditional",
    "桂林": "Guilin China karst mountains misty river scenic",
    "西藏": "Tibet China Himalayas Buddhist monastery dramatic landscape",
}

_VOCAB_MAP: dict[str, dict] = {
    "Russian": _RU,
    "Uzbek":   _UZ,
    "Arabic":  _AR,
    "Turkish": _TR,
    "Chinese": _ZH,
}


def expand_prompt(text: str, language: str) -> str:
    """Replace native vocabulary in `text` with English descriptors."""
    if language == "English" or language not in _VOCAB_MAP:
        return text

    vocab  = _VOCAB_MAP[language]
    result = text.lower()

    # Longest phrases first to avoid partial replacements
    for phrase in sorted(vocab, key=len, reverse=True):
        if phrase in result:
            result = result.replace(phrase, vocab[phrase])

    return re.sub(r"\s{2,}", " ", result).strip()
