STYLES = {
    "realistic":   {"label": "Realistic",     "emoji": "📷", "suffix": "photorealistic, 4k, highly detailed, sharp focus"},
    "anime":       {"label": "Anime",          "emoji": "🎌", "suffix": "anime style, manga, vibrant colors, studio ghibli"},
    "oil_painting":{"label": "Oil Painting",   "emoji": "🎨", "suffix": "oil painting, classical art, canvas texture, brush strokes"},
    "watercolor":  {"label": "Watercolor",     "emoji": "💧", "suffix": "watercolor painting, soft edges, pastel colors, artistic"},
    "cartoon":     {"label": "Cartoon",        "emoji": "✏️", "suffix": "cartoon style, colorful, fun, bold outlines, pixar style"},
    "cyberpunk":   {"label": "Cyberpunk",      "emoji": "🌆", "suffix": "cyberpunk, neon lights, futuristic city, dark atmosphere, sci-fi"},
    "fantasy":     {"label": "Fantasy",        "emoji": "🐉", "suffix": "fantasy art, magical, epic, detailed, dramatic lighting"},
    "sketch":      {"label": "Pencil Sketch",  "emoji": "✏️", "suffix": "pencil sketch, black and white, hand drawn, detailed linework"},
    "3d_render":   {"label": "3D Render",      "emoji": "💎", "suffix": "3d render, octane render, cinema4d, highly detailed, glossy"},
    "vintage":     {"label": "Vintage",        "emoji": "📸", "suffix": "vintage photography, retro, film grain, faded colors, 1970s"},
}

SIZES = {
    "square":    {"label": "Square (1:1)",    "w": 1024, "h": 1024},
    "portrait":  {"label": "Portrait (3:4)",  "w": 768,  "h": 1024},
    "landscape": {"label": "Landscape (16:9)","w": 1280, "h": 720},
    "wide":      {"label": "Wide (2:1)",       "w": 1280, "h": 640},
}

RANDOM_PROMPTS = [
    "A dragon flying over a misty mountain at dawn",
    "Ancient library with floating books and candles",
    "Underwater city with glowing coral and mermaids",
    "A lone astronaut on a purple alien planet",
    "Enchanted forest with glowing mushrooms at night",
    "Wolf howling at a massive full moon in winter",
    "A phoenix rising from golden flames",
    "Futuristic Tokyo city at night in heavy rain",
    "A wizard casting spells in a dark stone tower",
    "A fairy tale castle on top of a waterfall",
    "Золотой закат над горами, одинокий волк воет на луну",
    "Древний замок в густом лесу, туман и тайна",
    "Дракон над заснеженными горами на рассвете",
    "Registon maydoni kechqurun, oltin osmon va yulduzlar",
    "Samarqand ko'k gumbazlari, bahor va gullar",
    "Bo'ri qorda, tog'lar va to'lin oy",
    "Navro'z bayrami, atlas ko'ylaklar va gullar",
]

SUGGESTIONS = {
    "a ":     ["a dragon", "a castle", "a forest", "a warrior", "a city", "a phoenix", "a wolf", "a wizard"],
    "dark":   ["dark forest", "dark castle", "dark sky", "dark ocean", "dark fantasy"],
    "golden": ["golden sunset", "golden dragon", "golden city", "golden hour"],
    "ancient":["ancient temple", "ancient city", "ancient forest", "ancient dragon"],
    "futur":  ["futuristic city", "futuristic robot", "futuristic space station"],
    "cyber":  ["cyberpunk city", "cyberpunk girl", "cyberpunk street"],
    "night":  ["night city", "night forest", "night sky", "night market"],
    "space":  ["space station", "space battle", "space explorer", "space nebula"],
    "drag":   ["dragon flying", "dragon fire", "dragon cave", "dragon mountain"],
    "snow":   ["snowy mountains", "snowy forest", "snow storm", "snow castle"],
    "зак":    ["закат над горами", "закат в пустыне", "золотой закат"],
    "дра":    ["дракон над горами", "дракон и замок"],
    "лес":    ["лес в тумане", "лес ночью"],
    "tog":    ["tog'lar ustida", "tog' qori", "tog' ko'li"],
    "nav":    ["Navro'z bayrami", "Navro'z va gullar"],
}

# ── Language vocabularies ──────────────────────────────────────────────

RU_VOCAB = {
    "закат": "golden sunset warm orange red sky horizon",
    "рассвет": "dawn sunrise soft pink purple morning sky",
    "небо": "vast open sky", "облака": "dramatic clouds",
    "море": "ocean sea with waves", "река": "flowing river reflections",
    "лес": "dense forest tall trees", "гора": "majestic mountain peak",
    "горы": "mountain range snow-capped peaks dramatic",
    "степь": "vast open steppe grassland endless horizon wind",
    "пустыня": "desert sand dunes dry heat",
    "снег": "snow covered landscape white winter",
    "туман": "mysterious fog and mist ethereal",
    "звёзды": "starry night sky milky way galaxy",
    "звезды": "starry night sky milky way galaxy",
    "луна": "full moon glowing silver light",
    "солнце": "bright shining sun rays warm",
    "цветы": "colorful blooming flowers garden",
    "дерево": "ancient tall tree majestic",
    "водопад": "powerful waterfall cascading mist",
    "озеро": "calm reflective lake serene",
    "волк": "lone wolf fierce wild",
    "медведь": "brown bear powerful wild",
    "орёл": "eagle soaring wings spread sky",
    "орел": "eagle soaring wings spread sky",
    "лошадь": "majestic horse running mane flowing",
    "кони": "wild horses galloping mane flowing",
    "тигр": "fierce tiger striped jungle",
    "дракон": "dragon fire scales wings fantasy",
    "девушка": "young beautiful woman",
    "воин": "warrior battle-ready armor",
    "рыцарь": "armored knight medieval",
    "грусть": "melancholic sad mood somber tones",
    "радость": "joyful bright cheerful warm atmosphere",
    "тишина": "peaceful serene silent calm",
    "душа": "soulful spiritual deeply emotional ethereal",
    "мечта": "dreamlike ethereal surreal soft light",
    "тайна": "mysterious secret hidden ancient",
    "золотой": "golden shimmering warm",
    "золотая": "golden shimmering warm",
    "красный": "vivid deep red", "синий": "deep rich blue",
    "зелёный": "lush vibrant green", "белый": "pure brilliant white",
    "чёрный": "deep matte black",
    "москва": "Moscow Russia Red Square Kremlin golden domes",
    "байкал": "Lake Baikal Siberia crystal blue water",
    "замок": "medieval stone castle fortress dramatic",
    "церковь": "Russian Orthodox church colorful onion domes",
    "ночь": "night time dark moonlit",
    "зима": "winter cold snow ice frozen",
    "лето": "summer warm green sunny vibrant",
    "весна": "spring fresh blossoming flowers new life",
    "осень": "autumn fall golden orange leaves",
    "древний": "ancient old historical worn stone",
    "огромный": "enormous massive towering",
    "красивый": "beautiful stunning gorgeous",
    "мрачный": "gloomy dark somber brooding",
    "дикий": "wild untamed raw primal",
    "одинокий": "lone solitary isolated",
    "величественный": "majestic grand impressive awe-inspiring",
}

UZ_VOCAB = {
    "quyosh": "bright shining sun warm rays",
    "oy": "glowing full moon silver light",
    "yulduzlar": "starry night sky milky way stars",
    "osmon": "vast open sky blue",
    "tog": "majestic mountain peak rocky",
    "tog'": "majestic mountain peak rocky",
    "toglar": "mountain range dramatic snow peaks",
    "tog'lar": "mountain range dramatic snow peaks",
    "daryo": "flowing river peaceful reflections",
    "ko'l": "calm serene lake reflections",
    "dengiz": "ocean sea waves horizon",
    "cho'l": "desert sand dunes hot dry",
    "qor": "snow white landscape winter",
    "gul": "beautiful blooming flower",
    "gullar": "colorful flowers blooming garden",
    "bo'ri": "lone wolf fierce wild",
    "burgut": "eagle soaring wings spread majestic",
    "sher": "powerful lion savanna mane",
    "tuya": "camel desert Silk Road caravan",
    "navro'z": "Navruz spring festival Uzbekistan colorful atlas dresses sumalak celebrations flowers festive",
    "navruz": "Navruz spring festival Uzbekistan colorful atlas dresses sumalak celebrations flowers festive",
    "registon": "Registan square Samarkand blue mosaic tilework Islamic architecture historical",
    "samarqand": "ancient Samarkand city Silk Road blue domes minarets historical architecture",
    "buxoro": "ancient Bukhara historic walled city Kalon minaret tower desert sunset",
    "xiva": "Khiva Uzbekistan ancient Ichan-Kala walled city blue tile minarets",
    "ipak yo'li": "Silk Road ancient trade route Central Asia camels merchants desert",
    "karvon": "caravan camels merchants crossing vast desert Silk Road sunset",
    "atlas": "colorful Uzbek ikat atlas silk vibrant geometric patterns traditional textile",
    "chimyon": "Chimgan mountains Uzbekistan dramatic snow peaks green pine valleys",
    "masjid": "beautiful mosque blue dome minaret Islamic geometric tilework architecture",
    "oltin": "golden shimmering warm luxurious",
    "qizil": "vivid deep red", "ko'k": "deep rich blue",
    "yashil": "lush vibrant green", "oq": "pure brilliant white",
    "qora": "deep black dark", "sariq": "bright yellow warm sunny",
    "tun": "night dark moonlit",
    "qish": "winter cold snowy frozen landscape",
    "yoz": "summer warm sunny vibrant green",
    "bahor": "spring fresh blossoming flowers new life",
    "kuz": "autumn golden orange falling leaves",
    "ulkan": "enormous massive towering grand",
    "qadimiy": "ancient old historical",
    "chiroyli": "beautiful stunning gorgeous",
    "yolg'iz": "lone solitary isolated single",
    "buyuk": "great magnificent legendary",
    "sokin": "calm peaceful quiet serene",
    "go'zal": "beautiful stunning",
}

RU_CYRILLIC    = set("абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ")
UZ_CYR_UNIQUE  = set("ўқғҳ")
UZ_LATIN_WORDS = {
    "tog", "tog'", "qor", "gul", "ko'l", "bo'ri", "burgut",
    "navruz", "navro'z", "registon", "samarqand", "buxoro", "xiva",
    "toshkent", "chimyon", "plov", "atlas", "suzani", "do'ppi",
    "cho'l", "daryo", "osmon", "quyosh", "bahor", "kuz", "yoz", "qish",
    "chiroyli", "go'zal", "buyuk", "ulkan", "sokin", "yolg'iz",
    "qadimiy", "karvon", "ipak", "masjid", "oltin", "baxt", "orzu",
}
